
#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorA,          flipper,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if(SensorValue(sound) >= 50)
		{
			motor[flipper] = -40;
			wait10Msec(20);
			motor[flipper]= 0;

		}
	}
}

