#pragma config(Sensor, S1,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          flipper,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int presscount = 0;
	while(true)
	{
		while(SensorValue(button) == 1)
		{
			displayTextLine(4,"presscount: %d", presscount);
		}
			presscount= presscount + 1;
			wait10Msec(1);
			while(SensorValue(button) == 0)
			{
displayTextLine(4,"presscount: %d", presscount);
}
displayTextLine(4,"presscount: %d", presscount);
		}
	}
