#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorA,          flipper,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int clapcount = 0;

	while(true)
	{
		if(SensorValue(sound) >= 80)
		{
			clapcount= clapcount + 1;
			displayTextLine(4,"clapcount: %d", clapcount);
			wait10Msec(30);

			// || means "or"
			// 156 wait is 2 rotations
			// 75 works for one rotation
			// 41.5 for half rotation
			if(clapcount == 2 || clapcount == 4 || clapcount == 4 || clapcount == 6 || clapcount == 8 || clapcount == 10 )
			{
				motor[flipper] = -50;
				wait10Msec(40.7);
				motor[flipper]= 0;

			if(clapcount == 10)
				clapcount= 0;

}
}
}
}
