
#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorA,          flipper,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

			motor[flipper] = -60;
			wait10Msec(30);
			motor[flipper]= 0;
			motor[flipper] = 60;
			wait10Msec(30);
			motor[flipper]= 0;
			motor[flipper] = -60;
			wait10Msec(30);
			motor[flipper]= 0;
			motor[flipper] = 60;
			wait10Msec(30);
			motor[flipper]= 0;

		}
