
#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorA,          flipper,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

		motor[flipper] = -60;
		wait10Msec(35);

		motor[flipper]= 0;
		motor[flipper] = 60;
		wait10Msec(35);
		motor[flipper]= 0;
		motor[flipper] = -60;
		wait10Msec(35);
		motor[flipper]= 0;
		motor[flipper] = 60;
		wait10Msec(35
		);
		motor[flipper]= 0;
	}
}
