#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorA,          flipper,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
	{
		if(SensorValue(sound) >= 80)

			if(getTimerValue(timer1) <= 1000)
			{
				motor[flipper] = -50;
				wait10Msec(41);
				motor[flipper]= 0;
clearTimer(timer1);

			}
		}
	}
