#pragma config(Sensor, S1,     sound,          sensorSoundDB)
#pragma config(Motor,  motorA,          flipper,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void thru()
{

	if(getTimerValue(T1) < 1000)
			motor[flipper] = -50;
				wait10Msec(41);
				motor[flipper]= 0;
				clearTimer(T1);

}
	task main()
	{

		int clapcount = 0;
		while(true)
		{
			if(SensorValue(sound) >= 80)
			{
				clapcount= clapcount + 1;
				wait1Msec(10);
				displayTextLine(4,"clapcount: %d", clapcount);
				wait10Msec(30);
				thru();

}
}
}
